Homework1
made-ml-in-prod-2021/averpower pull request #1
Opened 2021-05-09 17:17 UTC by AverPower

Проект сделан по классической (описанной на лекции) схеме.

Обучение и предикт осуществляются в основном файле main_pipeline.py, в качестве аргумента поступает конфиг файл
В случае обучения в конфиге содержатся все основные пути (для логов, для поступающих данных, для сохранения  конечных резульатотв, трансформера и итоговой модели), параметры сплита, параметры для подбоа параметров по сетке, перечисление категориальных и числовых признаков, модель для обучения, целевой признак.
В случае предикта в конфиге содержатся также все основные пути, целевой признак  и размер тестовой выборки. Тестовая выборка генерируется случайным образом на основе исходных данных.

Что касается самооценки работы:
Считаю, что работа сделана на 22 балла, плюс 1 дополнительный за самооценку=)
Не сделаны тесты, что затрагивает сразу несколько пунктов задания.

2021-05-12 11:43 UTC, AverPower commented
При ревью кода коллеги понял, что неправильно понял задание "положите код в папку ml_project" и положил весь проект в эту папку вместо того, чтоб положить только основной код проекта.
Исправил это и соответственно описание структуры проекта в README.md в последних двух коммитах.
Прошу не снижать баллы за эту оплошность, уважаемые ревьюеры.

2021-05-13 19:55 UTC, ol-ga-00 commented
> При ревью кода коллеги понял, что неправильно понял задание "положите код в папку ml_project" и положил весь проект в эту папку вместо того, чтоб положить только основной код проекта.
> Исправил это и соответственно описание структуры проекта в README.md в последних двух коммитах.
> Прошу не снижать баллы за эту оплошность, уважаемые ревьюеры.

@AverPower, вы правильно поняли задание "положите код в папку ml_project"! 
В папке ml_project должна находиться вся первая домашка!
Так что прошу откатить два последних коммита
И прошу сообщить, у какого коллеги вы ревьювели код

2021-05-14 08:06 UTC, AverPower commented
> > При ревью кода коллеги понял, что неправильно понял задание "положите код в папку ml_project" и положил весь проект в эту папку вместо того, чтоб положить только основной код проекта.
> > Исправил это и соответственно описание структуры проекта в README.md в последних двух коммитах.
> > Прошу не снижать баллы за эту оплошность, уважаемые ревьюеры.
> 
> @AverPower, вы правильно поняли задание "положите код в папку ml_project"!
> В папке ml_project должна находиться вся первая домашка!
> Так что прошу откатить два последних коммита
> И прошу сообщить, у какого коллеги вы ревьювели код


Откатил два последних коммита.
Ревью делал в репозитории https://github.com/made-ml-in-prod-2021/ilyua

2021-05-15 09:14 UTC, ol-ga-00 requested changes
На будущее -- бинарные файлы лучше не коммитеть (logistic_regression_model.pkl, transformer.pkl)
Но так как это тестовое задание -- то можете их здесь оставить

2021-05-15 09:14 UTC, ol-ga-00 commented on ml_project/src/main_pipeline.py
> +    predictions = model.predict(transformed_features)
Предлагаю использовать predict_model из models.model_fit_predict

2021-05-15 09:14 UTC, ol-ga-00 commented on ml_project/src/main_pipeline.py
> +    test_data = generate_fake_data(data, params.test_data_size)
Не понимаю, зачем данные, на основе которых нужно сделать предсказание, преобразуются при помощи библиотеки Faker 
Эту библиотеку используют для генерации синтетики (для тестов). А здесь происходит предсказание, данные должны быть реальными

Если я что-то понимаю не так, то прошу пояснить

2021-05-15 09:14 UTC, ol-ga-00 commented on ml_project/data/raw/data.xls
> +﻿age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
Почему .xls, а не .csv?
Вопрос чисто из любопытства

2021-05-15 11:50 UTC, AverPower commented on ml_project/src/main_pipeline.py
> +    predictions = model.predict(transformed_features)
Принято!

2021-05-15 11:52 UTC, AverPower commented on ml_project/src/main_pipeline.py
> +    test_data = generate_fake_data(data, params.test_data_size)
Да, согласен. 
Не успевал заняться тестами для всего проекта, решил добавить для наглядности работы
Понимаю, что это ни к чему
Уберу

2021-05-15 11:56 UTC, AverPower commented on ml_project/data/raw/data.xls
> +﻿age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
Не знаю вообще, как так вышло, ведь в исходнике был именно .csv
Исправлю

2021-05-15 11:58 UTC, AverPower commented
> На будущее -- бинарные файлы лучше не коммитеть (logistic_regression_model.pkl, transformer.pkl)
> Но так как это тестовое задание -- то можете их здесь оставить

А можно тогда вопрос?
Для чего тогда в структуре проекта папка models - что в нее коммитить? Или ее оставляют пустой?

2021-05-15 12:02 UTC, AverPower commented on ml_project/src/main_pipeline.py
> +    test_data = generate_fake_data(data, params.test_data_size)
А, я вспомнил, что меня смутило. Не очень понятно, в каком формате придут данные для предикта.
И мне не понятно в таком случае, в чем сложность пункта задания, где нужно написать функцию для предикта модели

2021-05-17 08:15 UTC, AverPower commented
@ol-ga-00 
Все указанные замечания устранил

2021-05-22 18:50 UTC, ol-ga-00 commented on ml_project/src/main_pipeline.py
> +    test_data = generate_fake_data(data, params.test_data_size)
Сложности в том пункте нет :)

2021-05-22 18:52 UTC, ol-ga-00 commented
> > На будущее -- бинарные файлы лучше не коммитеть (logistic_regression_model.pkl, transformer.pkl)
> > Но так как это тестовое задание -- то можете их здесь оставить
> 
> А можно тогда вопрос?
> Для чего тогда в структуре проекта папка models - что в нее коммитить? Или ее оставляют пустой?

Да, её оставляют пустой
Она нужна, чтобы при клонировании, её не приходилось создавать

2021-05-22 18:59 UTC, ol-ga-00 approved these changes
Ставлю 23 балла

2021-05-24 06:43 UTC, AverPower commented
> Ставлю 23 балла

Спасибо за уделенное время!

2021-05-27 13:11 UTC, ol-ga-00 commented
Предлагаю не ждать @MikhailYeka 
@AverPower, можете мёржить

2021-05-27 13:13 UTC, merged