Homework3
made-ml-in-prod-2021/averpower pull request #3
Opened 2021-06-04 11:13 UTC by AverPower

Homework #3 
![1](https://user-images.githubusercontent.com/48547158/120792958-f260b380-c53e-11eb-9af3-4691b0313c8d.jpg)
![2](https://user-images.githubusercontent.com/48547158/120792960-f391e080-c53e-11eb-9da8-24640afaa2c5.jpg)
![3](https://user-images.githubusercontent.com/48547158/120792961-f391e080-c53e-11eb-9723-2333c63d1ed7.jpg)
![4](https://user-images.githubusercontent.com/48547158/120792963-f42a7700-c53e-11eb-84f1-aa3ddb373d4d.jpg)

2021-06-04 14:32 UTC, cherninkiy commented
Привет. Я пока сам не до конца разобрался, review не смогу сделать. Убери меня, запроси другого.

2021-06-04 17:07 UTC, Mikhail-M requested changes
верните code ml_project
сделайте норм название дагов

2021-06-06 20:04 UTC, ioiein requested changes
Все реализовано корректно: запускается и работает. Сенсоры реализованы на проверку наличия директорий, а не на файлы( в задании написано: Реализуйте сенсоры на то, что данные готовы для дагов тренировки и обучения, насколько я понимаю нужно чекать файлы, но возможно это я не совсем правильно понял). В остальном со всем согласен.

2021-06-06 20:04 UTC, ioiein commented on airflow_ml_dags/dags/dag_1.py
> +default_args = {
defailt_args и другие повторяющиеся переменные можно вынести в отдельный файл(например constants.py и импортить их оттуда)

2021-06-06 20:04 UTC, ioiein commented on airflow_ml_dags/dags/dag_2.py
> +def _wait_for_file():
1) название не соответствует функции, тут проверяется наличие директории, а не файла
2) В задании нужно проверить готовность материалов для обучения, тут же просто проверяется существование папки

2021-06-06 20:04 UTC, ioiein commented on airflow_ml_dags/dags/dag_3.py
> +def _wait_for_file():
аналогично написанному выше

2021-06-07 09:16 UTC, AverPower commented
> верните code ml_project
> сделайте норм название дагов

Исправлено

2021-06-07 09:16 UTC, AverPower commented on airflow_ml_dags/dags/dag_1.py
> +default_args = {
Исправлено

2021-06-07 09:16 UTC, AverPower commented on airflow_ml_dags/dags/dag_2.py
> +def _wait_for_file():
Исправлено

2021-06-07 09:16 UTC, AverPower commented on airflow_ml_dags/dags/dag_3.py
> +def _wait_for_file():
Исправлено

2021-06-07 15:37 UTC, ioiein approved these changes
Стоит изменить названия тестов аналогично названиям дагов. В остальном все ок.

2021-06-07 15:37 UTC, ioiein commented on airflow_ml_dags/tests/test_airflow.py
>  def test_first_dag_loaded(dags):
Было бы более информативно сделать названия тестов соответствующие названиям дагов.

2021-06-08 05:32 UTC, AverPower commented on airflow_ml_dags/tests/test_airflow.py
>  def test_first_dag_loaded(dags):
Согласен, исправлю

2021-06-08 16:30 UTC, ioiein approved these changes

2021-07-01 19:35 UTC, Mikhail-M approved these changes
Баллы: 39

2021-07-01 19:50 UTC, AverPower commented
Merged homework 3

2021-07-01 19:52 UTC, merged